# Generated by Django 2.2.1 on 2019-09-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
