# Generated by Django 2.2.4 on 2019-09-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0009_remove_seat_zone'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('unitprice', models.CharField(max_length=50)),
                ('totalprice', models.CharField(max_length=50)),
                ('orderby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.Table')),
                ('orderitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.MenuCard')),
            ],
        ),
    ]
