# Generated by Django 2.2.4 on 2019-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kotstatus',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'pass')], default=0),
        ),
    ]
