# Generated by Django 2.2.4 on 2019-09-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190926_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='kotstatus',
            field=models.CharField(choices=[(0, 'pending'), (1, 'pass')], default=0, max_length=20),
        ),
    ]
