# Generated by Django 2.2.4 on 2019-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190926_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='kotstatus',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'pass')], default=0),
        ),
    ]
