# Generated by Django 2.2.4 on 2019-10-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('outlet_zone', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
