# Generated by Django 2.2.1 on 2019-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_auto_20190915_0713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('name', 'outlet')},
        ),
    ]
