# Generated by Django 2.2.1 on 2019-09-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_auto_20190916_0802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('name_or_number', 'table')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('name', 'zone')},
        ),
    ]
