# Generated by Django 2.2.4 on 2019-09-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_outlet_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
