# Generated by Django 2.2.4 on 2019-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_auto_20190918_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('name', 'table')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='name_or_number',
        ),
    ]
