# Generated by Django 2.2.4 on 2019-09-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0007_auto_20190918_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spaces.Zone'),
            preserve_default=False,
        ),
    ]
