# Generated by Django 2.2.4 on 2019-09-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_seat_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='zone',
        ),
    ]
